version: '2'
services:
  server:
    build: ./server
    ports:
      - '5000:5000'
    restart: always
    container_name: server
  client:
    build: ./client
    ports:
      - '80:80'
    restart: always
    container_name: client
