version: '3'
services:
  #############
  ## SERVER ##
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - webapp
      - database
    depends_on:
      - postgres_db
    command: ['./wait-for-it.sh', 'postgres_db:5432', '--', 'node', 'index']
    container_name: server
  #############
  ## CLIENT ##
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - webapp
    ports:
      - '80:80'
    links:
      - server
    container_name: client
  ##############
  ## POSTGRES ##
  postgres_db:
    image: postgres
    networks:
      - database
    env_file:
      - ./database/.env
    volumes:
      - ./database/db_data:/var/lib/postgresql/data/
      - ./database/initdb.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: postgres_db

networks:
  webapp:
    driver: bridge
  database:
    driver: bridge
