version: '3.7'
services:
  ##############
  ## POSTGRES ##
  postgres_db:
    image: postgres
    networks:
      - database
    ports:
      - 5432:5432
    env_file:
      - ./database/.env
    restart: always
    volumes:
      - ./database/data/dev:/var/lib/postgresql/data
      - ./database/initdb.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: postgres_db
  ##############
  ## SERVER ##
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    networks:
      - webapp
      - database
    ports:
      - 5500:5500
    env_file:
      - ./server/.env
    volumes:
      - ./server/src:/app/src
    links:
      - postgres_db
    depends_on:
      - postgres_db
    restart: always
    command: ['./wait-for-it.sh', 'postgres_db:5432', '--', 'nodemon']
    container_name: server
  #############
  ## CLIENT ##
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    env_file:
      - ./client/.env
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
    networks:
      - webapp
    ports:
      - 3000:3000
    command: npm start
    links:
      - server
    stdin_open: true
    restart: always
    container_name: client
networks:
  webapp:
    driver: bridge
  database:
    driver: bridge
