version: '3'
services:
  server:
    build: ./server
    networks:
      - webapp
    container_name: server
  client:
    build: ./client
    networks:
      - webapp
    ports:
      - '80:80'
    container_name: client

networks:
  webapp:
    driver: bridge
