version: '3'
services:
  #############
  ## SERVER ##
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - webapp
      - database
    depends_on:
      - postgres_db
    links:
      - postgres_db
    env_file:
      - ./server/.env
    restart: always
    command: ['./wait-for-it.sh', 'postgres_db:5432', '--', 'node', 'index.js']
    container_name: server
  #############
  ## CLIENT ##
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - webapp
    ports:
      - 80:80
    links:
      - server
    restart: always
    container_name: client
  ##############
  ## POSTGRES ##
  postgres_db:
    image: postgres
    networks:
      - database
    env_file:
      - ./database/.env
    volumes:
      - ./database/data/dev:/var/lib/postgresql/data/
      - ./database/initdb.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    restart: always
    container_name: postgres_db

networks:
  webapp:
    driver: bridge
  database:
    driver: bridge
